--------------------------------------------------------------------------------
------- 1 - ZAPYTANIE WYSWIETLA INFORMACJE O GOLACH MECZU O PODANYM ID ---------
--------------------------------------------------------------------------------
SELECT
ID_MECZU, 
DATA_MECZU, 
CZAS_MECZU,
(SELECT KLUB.NAZWA FROM DRUZYNA join klub on KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU WHERE MECZ.DRUZYNA_ID_DRUZYNY_1 = DRUZYNA.ID_DRUZYNY ) as KLUB_1,
(SELECT KLUB.NAZWA FROM DRUZYNA join klub on KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU WHERE MECZ.DRUZYNA_ID_DRUZYNY_2 = DRUZYNA.ID_DRUZYNY ) as KLUB_2,
(SELECT STADION.NAZWA FROM STADION WHERE MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU) as STADION,
(SELECT STADION.LOKALIZACJA FROM STADION WHERE MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU) as LOKALIZACJA
FROM MECZ;

SELECT
  ZDARZENIE.CZAS,
  OSOBA.NAZWISKO AS NAZWISKO_ZAWODNIKA,
  OSOBA.IMIE AS IMIE_ZAWODNIKA
FROM ZDARZENIE
  JOIN ZAWODNIK_MECZ 
    ON ZDARZENIE.ZAWODNIK_1_ID_OSOBY = ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY
    AND ZDARZENIE.MECZ_ID_MECZU = ZAWODNIK_MECZ.MECZ_ID_MECZU
  JOIN DRUZYNA 
    ON DRUZYNA.ID_DRUZYNY = ZAWODNIK_MECZ.DRUZYNA_ID_DRUZYNY
  JOIN KLUB
    ON KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU
  JOIN OSOBA
    ON OSOBA.ID_OSOBY = ZDARZENIE.ZAWODNIK_1_ID_OSOBY 
  WHERE ZDARZENIE.MECZ_ID_MECZU = &Podaj_Id_Meczu
    AND ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4000
GROUP BY 
  KLUB.NAZWA, 
  ZDARZENIE.TYP_ZDARZENIA_ID_TYPU,
  OSOBA.IMIE,
  OSOBA.NAZWISKO,
  ZDARZENIE.CZAS
ORDER BY KLUB.NAZWA;
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------