--------------------------------------------------------------------------------
-------------- 3 - FUNKCJA ZWRACA NAZWY KLUBOW I WYNIK W MECZU -----------------
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION FUN_WYNIK_MECZU (ID_M IN INTEGER) 
RETURN VARCHAR2 IS

  TMP_WYNIK_KLUB_1  INTEGER := 0;
  TMP_WYNIK_KLUB_2  INTEGER := 0;
  TMP_NAZWA_KLUB_1  VARCHAR(30) := '';
  TMP_NAZWA_KLUB_2  VARCHAR(30) := '';
  TMP_TMP           VARCHAR(30) := '';

--KURSOR Z NAZWAMI KLUBOW W MECZU
CURSOR CUR_KLUBY_MECZU IS SELECT DISTINCT

  KLUB.NAZWA AS NAZWA_KLUBU

FROM MECZ

  JOIN DRUZYNA 
    ON DRUZYNA.ID_DRUZYNY = MECZ.DRUZYNA_ID_DRUZYNY_1
    OR DRUZYNA.ID_DRUZYNY = MECZ.DRUZYNA_ID_DRUZYNY_2
  JOIN KLUB
    ON KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU

  WHERE MECZ.ID_MECZU = ID_M
     
ORDER BY KLUB.NAZWA DESC;
 
--KURSOR Z NAZWAMI KLUBOW I LICZBA GOLI    
CURSOR CUR_GOLE_KLUBY_MECZU IS SELECT DISTINCT
  
  KLUB.NAZWA,
  COUNT (*) AS ILOSC_GOLI

FROM ZDARZENIE

  JOIN ZAWODNIK_MECZ 
    ON ZDARZENIE.ZAWODNIK_1_ID_OSOBY = ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY
    AND ZDARZENIE.MECZ_ID_MECZU = ZAWODNIK_MECZ.MECZ_ID_MECZU
  JOIN DRUZYNA 
    ON DRUZYNA.ID_DRUZYNY = ZAWODNIK_MECZ.DRUZYNA_ID_DRUZYNY
  JOIN TYP_ZDARZENIA 
    ON ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = TYP_ZDARZENIA.ID_TYPU
  JOIN KLUB
    ON KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU

  WHERE ZDARZENIE.MECZ_ID_MECZU = ID_M
    AND ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4000
    
GROUP BY 
  KLUB.NAZWA,
  ZDARZENIE.TYP_ZDARZENIA_ID_TYPU

ORDER BY KLUB.NAZWA DESC;

BEGIN

  OPEN CUR_KLUBY_MECZU;
  FETCH CUR_KLUBY_MECZU INTO TMP_NAZWA_KLUB_1;
  FETCH CUR_KLUBY_MECZU INTO TMP_NAZWA_KLUB_2;
  CLOSE CUR_KLUBY_MECZU;

  OPEN CUR_GOLE_KLUBY_MECZU;
  
  --JESLI NIE BEDZIE GOLI TO ZOSTANIE ZERO
  FETCH CUR_GOLE_KLUBY_MECZU INTO TMP_TMP, TMP_WYNIK_KLUB_1;
  
  --JESLI NIE BEDZIE GOLI TO ZOSTANIE ZERO
  FETCH CUR_GOLE_KLUBY_MECZU INTO TMP_TMP, TMP_WYNIK_KLUB_2;
 
  CLOSE CUR_GOLE_KLUBY_MECZU;
  
  RETURN
  (
    TO_CHAR
    (
      TMP_NAZWA_KLUB_1 || ' ' || 
      TO_CHAR(TMP_WYNIK_KLUB_1) || ' : ' || 
      TO_CHAR(TMP_WYNIK_KLUB_2) || ' ' || 
      TMP_NAZWA_KLUB_2
    )
  );
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

SELECT
ID_MECZU, 
DATA_MECZU, 
CZAS_MECZU,
(SELECT KLUB.NAZWA FROM DRUZYNA join klub on KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU WHERE MECZ.DRUZYNA_ID_DRUZYNY_1 = DRUZYNA.ID_DRUZYNY ) as KLUB_1,
(SELECT KLUB.NAZWA FROM DRUZYNA join klub on KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU WHERE MECZ.DRUZYNA_ID_DRUZYNY_2 = DRUZYNA.ID_DRUZYNY ) as KLUB_2,
(SELECT STADION.NAZWA FROM STADION WHERE MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU) as STADION,
(SELECT STADION.LOKALIZACJA FROM STADION WHERE MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU) as LOKALIZACJA
FROM MECZ;

BEGIN

  DBMS_OUTPUT.PUT_LINE(FUN_WYNIK_MECZU(&Podaj_Id_Meczu));

END;
/
