--------------------------------------------------------------------------------
--- 4 - FUNKCJA ZWRACA PROCENT ZDARZENIA WZGLEDEM WSZYSTKICH ZDARZEN W MECZU ---
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE 
FUNCTION FUN_PROC_ZDARZENIE_MECZ (ID_M IN INTEGER, ID_Z IN INTEGER) 
RETURN INTEGER IS

  TMP_ILOSC_WSZYSTKICH_ZDARZEN INTEGER;
  TMP_ILOSC_WSKAZANYCH_ZDARZEN INTEGER;

BEGIN

  SELECT 
    COUNT(*) INTO TMP_ILOSC_WSZYSTKICH_ZDARZEN 
  FROM ZDARZENIE 
  WHERE MECZ_ID_MECZU = ID_M;
  
  SELECT 
    COUNT(*) INTO TMP_ILOSC_WSKAZANYCH_ZDARZEN 
  FROM ZDARZENIE 
  WHERE MECZ_ID_MECZU = ID_M
    AND TYP_ZDARZENIA_ID_TYPU = ID_Z;
  
  
  RETURN((TMP_ILOSC_WSKAZANYCH_ZDARZEN/TMP_ILOSC_WSZYSTKICH_ZDARZEN)*100);
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

SELECT ID_TYPU, NAZWA FROM TYP_ZDARZENIA;

SELECT
ID_MECZU, 
DATA_MECZU, 
CZAS_MECZU,
(SELECT KLUB.NAZWA FROM DRUZYNA join klub on KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU WHERE MECZ.DRUZYNA_ID_DRUZYNY_1 = DRUZYNA.ID_DRUZYNY ) as KLUB_1,
(SELECT KLUB.NAZWA FROM DRUZYNA join klub on KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU WHERE MECZ.DRUZYNA_ID_DRUZYNY_2 = DRUZYNA.ID_DRUZYNY ) as KLUB_2,
(SELECT STADION.NAZWA FROM STADION WHERE MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU) as STADION,
(SELECT STADION.LOKALIZACJA FROM STADION WHERE MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU) as LOKALIZACJA
FROM MECZ;


BEGIN

  DBMS_OUTPUT.PUT_LINE
  (
    'Wybrane Zdarzenie Stanowi ' ||
    TO_CHAR(FUN_PROC_ZDARZENIE_MECZ(&Id_Meczu,&Id_Typu_Zdarzenia)) ||
    ' % Wszystkich Zdarzen W Tym Meczu'
  );
  
END;
/