--Usuniecie Sekwencji
DROP SEQUENCE POZYCJA_SEQ;
DROP SEQUENCE OSOBA_SEQ;
DROP SEQUENCE KLUB_SEQ;
DROP SEQUENCE TYP_SEQ;
DROP SEQUENCE STADION_SEQ;
DROP SEQUENCE DRUZYNA_SEQ;
DROP SEQUENCE MECZ_SEQ;
DROP SEQUENCE KLASA_SEDZIEGO_SEQ;
DROP SEQUENCE SEDZIA_SEQ;
DROP SEQUENCE ZDARZENIE_SEQ;
DROP SEQUENCE LOG_SEQ;

--Opró¿nienie kosza
PURGE RECYCLEBIN;