--Usuniecie Funkcji
DROP FUNCTION FUN_AVG_WIEKU_ZAW_KLUBU;
DROP FUNCTION FUN_MECZ_ILOSC_KARTEK;
DROP FUNCTION FUN_WYNIK_MECZU;
DROP FUNCTION FUN_PROC_ZDARZENIE_MECZ;

--Opró¿nienie kosza
PURGE RECYCLEBIN;