--Usuniecie Tabel
DROP TABLE ZDARZENIE;
DROP TABLE TYP_ZDARZENIA;
DROP TABLE ZAWODNIK_MECZ;
DROP TABLE MECZ;
DROP TABLE STADION;
DROP TABLE DRUZYNA;
DROP TABLE KLUB;
DROP TABLE SEDZIA_MECZ;
DROP TABLE OSOBA;
DROP TABLE POZYCJA;
DROP TABLE KLASA_SEDZIEGO;
DROP TABLE OSOBA_LOG;

--Opró¿nienie kosza
PURGE RECYCLEBIN;