
--Usuniecie Tabel
DROP TABLE ZDARZENIE;
DROP TABLE TYP_ZDARZENIA;
DROP TABLE ZAWODNIK_MECZ;
DROP TABLE MECZ;
DROP TABLE STADION;
DROP TABLE DRUZYNA;
DROP TABLE KLUB;
DROP TABLE SEDZIA_MECZ;
DROP TABLE OSOBA;
DROP TABLE POZYCJA;
DROP TABLE KLASA_SEDZIEGO;
DROP TABLE OSOBA_LOG;

--Usuniecie Sekwencji
DROP SEQUENCE POZYCJA_SEQ;
DROP SEQUENCE OSOBA_SEQ;
DROP SEQUENCE KLUB_SEQ;
DROP SEQUENCE TYP_SEQ;
DROP SEQUENCE STADION_SEQ;
DROP SEQUENCE DRUZYNA_SEQ;
DROP SEQUENCE MECZ_SEQ;
DROP SEQUENCE KLASA_SEDZIEGO_SEQ;
DROP SEQUENCE SEDZIA_SEQ;
DROP SEQUENCE ZDARZENIE_SEQ;
DROP SEQUENCE LOG_SEQ;

--Usuniecie Widokow
DROP VIEW ZAWODNIK_GOLE;
DROP VIEW STADION_INFO;
DROP VIEW SEDZIA_INFO;
DROP VIEW KLUBY_INFO;

--Usuniecie Funkcji
DROP FUNCTION FUN_AVG_WIEKU_ZAW_KLUBU;
DROP FUNCTION FUN_MECZ_ILOSC_KARTEK;
DROP FUNCTION FUN_WYNIK_MECZU;
DROP FUNCTION FUN_PROC_ZDARZENIE_MECZ;

--Usuniecie Wyzwalaczy
DROP TRIGGER TGR_KONTROLA_KARTEK;
DROP TRIGGER TGR_LOG_OSOBA;

--Opró¿nienie kosza
PURGE RECYCLEBIN;
