--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--Tworzenie Sekwencji
CREATE SEQUENCE KLASA_SEDZIEGO_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE POZYCJA_SEQ START WITH 200 INCREMENT BY 1;
CREATE SEQUENCE SEDZIA_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE OSOBA_SEQ START WITH 2000 INCREMENT BY 1;
CREATE SEQUENCE KLUB_SEQ START WITH 3000 INCREMENT BY 1;
CREATE SEQUENCE TYP_SEQ START WITH 4000 INCREMENT BY 1;
CREATE SEQUENCE STADION_SEQ START WITH 5000 INCREMENT BY 1;
CREATE SEQUENCE DRUZYNA_SEQ START WITH 6000 INCREMENT BY 1;
CREATE SEQUENCE MECZ_SEQ START WITH 7000 INCREMENT BY 1;
CREATE SEQUENCE ZDARZENIE_SEQ START WITH 8000 INCREMENT BY 1;
CREATE SEQUENCE LOG_SEQ START WITH 9000 INCREMENT BY 1;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE OSOBA_LOG
(
  ID_LOG            INTEGER NOT NULL ,
  DATA_ZMIANY       DATE,
  ID_OSOBY          INTEGER NOT NULL ,
  IMIE              VARCHAR2 (35) NOT NULL ,
  NAZWISKO          VARCHAR2 (20) NOT NULL ,
  DATA_URODZENIA    DATE NOT NULL ,
  MIEJSCE_URODZENIA VARCHAR2 (25) NOT NULL ,
  NARODOWOSC        VARCHAR2 (30) NOT NULL
) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE DRUZYNA
(
  ID_DRUZYNY    INTEGER NOT NULL ,
  NAZWA         VARCHAR2 (30) NOT NULL ,
  KLUB_ID_KLUBU INTEGER NOT NULL
) ;
  
ALTER TABLE DRUZYNA 
ADD CONSTRAINT DRUZYNA_PK 
PRIMARY KEY ( ID_DRUZYNY ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE KLASA_SEDZIEGO
(
  ID_KLASY    INTEGER NOT NULL ,
  NAZWA_KLASY VARCHAR2 (20) NOT NULL
) ;
  
ALTER TABLE KLASA_SEDZIEGO 
ADD CONSTRAINT KLASA_SEDZIEGO_PK 
PRIMARY KEY ( ID_KLASY ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE KLUB
(
  ID_KLUBU        INTEGER NOT NULL ,
  NAZWA           VARCHAR2 (30) NOT NULL ,
  DATA_ZALOZENIA  DATE NOT NULL ,
  SZEF_ID_OSOBY   INTEGER NOT NULL ,
  TRENER_ID_OSOBY INTEGER NOT NULL
) ;
  
ALTER TABLE KLUB 
ADD CONSTRAINT KLUB_PK 
PRIMARY KEY ( ID_KLUBU ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE MECZ
(
  ID_MECZU                      INTEGER NOT NULL ,
  DATA_MECZU                    DATE NOT NULL ,
  CZAS_MECZU                    VARCHAR2(6) NOT NULL ,
  DRUZYNA_ID_DRUZYNY_1          INTEGER NOT NULL ,
  DRUZYNA_ID_DRUZYNY_2          INTEGER NOT NULL ,
  STADION_ID_STADIONU           INTEGER NOT NULL ,
  SEDZIA_MECZ_ID_OSOBY_SEDZIA_1 INTEGER NOT NULL ,    
  SEDZIA_MECZ_ID_OSOBY_SEDZIA_2 INTEGER NOT NULL ,
  SEDZIA_MECZ_ID_OSOBY_SEDZIA_3 INTEGER NOT NULL 
) ;
  
ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_PK 
PRIMARY KEY ( ID_MECZU ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE OSOBA
(
  ID_OSOBY          INTEGER NOT NULL ,
  IMIE              VARCHAR2 (35) NOT NULL ,
  NAZWISKO          VARCHAR2 (20) NOT NULL ,
  DATA_URODZENIA    DATE NOT NULL ,
  MIEJSCE_URODZENIA VARCHAR2 (22) NOT NULL ,
  NARODOWOSC        VARCHAR2 (30) NOT NULL
) ;
ALTER TABLE OSOBA 
ADD CONSTRAINT OSOBA_PK 
PRIMARY KEY ( ID_OSOBY ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE POZYCJA
(
  ID_POZYCJI INTEGER NOT NULL ,
  NAZWA      VARCHAR2 (20) NOT NULL
) ;
  
ALTER TABLE POZYCJA 
ADD CONSTRAINT POZYCJA_PK 
PRIMARY KEY ( ID_POZYCJI ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE SEDZIA_MECZ
(
  ID_SEDZIEGO             INTEGER NOT NULL ,
  OSOBA_ID_OSOBY          INTEGER NOT NULL ,
  KLASA_SEDZIEGO_ID_KLASY INTEGER NOT NULL
) ;
ALTER TABLE SEDZIA_MECZ 
ADD CONSTRAINT SEDZIA_MECZ_PK 
PRIMARY KEY ( ID_SEDZIEGO ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE STADION
(
  ID_STADIONU   INTEGER NOT NULL ,
  NAZWA         VARCHAR2 (30) NOT NULL ,
  LOKALIZACJA   VARCHAR2 (20) NOT NULL ,
  KLUB_ID_KLUBU INTEGER NOT NULL
) ;

ALTER TABLE STADION 
ADD CONSTRAINT STADION_PK 
PRIMARY KEY ( ID_STADIONU ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE TYP_ZDARZENIA
(
  ID_TYPU INTEGER NOT NULL ,
  NAZWA   VARCHAR2 (20) NOT NULL
) ;
  
ALTER TABLE TYP_ZDARZENIA 
ADD CONSTRAINT TYP_ZDARZENIA_PK 
PRIMARY KEY ( ID_TYPU ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE ZAWODNIK_MECZ
(
  MECZ_ID_MECZU      INTEGER NOT NULL ,
  POZYCJA_ID_POZYCJI INTEGER NOT NULL ,
  ZAWODNIK_ID_OSOBY  INTEGER NOT NULL,
  DRUZYNA_ID_DRUZYNY INTEGER NOT NULL
) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CREATE TABLE ZDARZENIE
(
  ID_ZDARZENIA            INTEGER NOT NULL ,
  TYP_ZDARZENIA_ID_TYPU   INTEGER NOT NULL ,
  CZAS                    VARCHAR(6) NOT NULL ,
  ZAWODNIK_1_ID_OSOBY     INTEGER NOT NULL ,
  ZAWODNIK_2_ID_OSOBY     INTEGER ,
  MECZ_ID_MECZU           INTEGER NOT NULL ,
  SEDZIA_MECZ_ID_SEDZIEGO INTEGER NOT NULL
) ;
  
ALTER TABLE ZDARZENIE 
ADD CONSTRAINT ZDARZENIE_PK 
PRIMARY KEY ( ID_ZDARZENIA ) ;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

ALTER TABLE DRUZYNA 
ADD CONSTRAINT DRUZYNA_KLUB_FK 
FOREIGN KEY ( KLUB_ID_KLUBU ) 
REFERENCES KLUB ( ID_KLUBU ) ;

ALTER TABLE KLUB 
ADD CONSTRAINT KLUB_OSOBA_FK 
FOREIGN KEY ( SZEF_ID_OSOBY ) 
REFERENCES OSOBA ( ID_OSOBY ) ;

ALTER TABLE KLUB 
ADD CONSTRAINT KLUB_OSOBA_FKv1 
FOREIGN KEY ( TRENER_ID_OSOBY ) 
REFERENCES OSOBA ( ID_OSOBY ) ;

ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_DRUZYNA_FK 
FOREIGN KEY ( DRUZYNA_ID_DRUZYNY_1 ) 
REFERENCES DRUZYNA ( ID_DRUZYNY ) ;

ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_DRUZYNA_FKv1 
FOREIGN KEY ( DRUZYNA_ID_DRUZYNY_2 ) 
REFERENCES DRUZYNA ( ID_DRUZYNY ) ;

ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_SEDZIA_MECZ_FK 
FOREIGN KEY ( SEDZIA_MECZ_ID_OSOBY_SEDZIA_1 ) 
REFERENCES SEDZIA_MECZ ( ID_SEDZIEGO ) ;

ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_SEDZIA_MECZ_FKv1 
FOREIGN KEY ( SEDZIA_MECZ_ID_OSOBY_SEDZIA_2 ) 
REFERENCES SEDZIA_MECZ ( ID_SEDZIEGO ) ;

ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_SEDZIA_MECZ_FKv2 
FOREIGN KEY ( SEDZIA_MECZ_ID_OSOBY_SEDZIA_3 ) 
REFERENCES SEDZIA_MECZ ( ID_SEDZIEGO ) ;

ALTER TABLE MECZ 
ADD CONSTRAINT MECZ_STADION_FK 
FOREIGN KEY ( STADION_ID_STADIONU ) 
REFERENCES STADION ( ID_STADIONU ) ;

ALTER TABLE SEDZIA_MECZ 
ADD CONSTRAINT SEDZIA_MECZ_KLASA_SEDZIEGO_FK 
FOREIGN KEY ( KLASA_SEDZIEGO_ID_KLASY ) 
REFERENCES KLASA_SEDZIEGO ( ID_KLASY ) ;

ALTER TABLE SEDZIA_MECZ 
ADD CONSTRAINT SEDZIA_MECZ_OSOBA_FK 
FOREIGN KEY ( OSOBA_ID_OSOBY ) 
REFERENCES OSOBA ( ID_OSOBY ) ;

ALTER TABLE STADION 
ADD CONSTRAINT STADION_KLUB_FK 
FOREIGN KEY ( KLUB_ID_KLUBU ) 
REFERENCES KLUB ( ID_KLUBU ) ;

ALTER TABLE ZAWODNIK_MECZ 
ADD CONSTRAINT ZAWODNIK_MECZ_DRUZYNA_FK 
FOREIGN KEY ( DRUZYNA_ID_DRUZYNY ) 
REFERENCES DRUZYNA ( ID_DRUZYNY ) ;

ALTER TABLE ZAWODNIK_MECZ 
ADD CONSTRAINT ZAWODNIK_MECZ_MECZ_FK 
FOREIGN KEY ( MECZ_ID_MECZU ) 
REFERENCES MECZ ( ID_MECZU ) ;

ALTER TABLE ZAWODNIK_MECZ 
ADD CONSTRAINT ZAWODNIK_MECZ_OSOBA_FK 
FOREIGN KEY ( ZAWODNIK_ID_OSOBY ) 
REFERENCES OSOBA ( ID_OSOBY ) ;

ALTER TABLE ZAWODNIK_MECZ 
ADD CONSTRAINT ZAWODNIK_MECZ_POZYCJA_FK 
FOREIGN KEY ( POZYCJA_ID_POZYCJI ) 
REFERENCES POZYCJA ( ID_POZYCJI ) ;

ALTER TABLE ZDARZENIE 
ADD CONSTRAINT ZDARZENIE_MECZ_FK 
FOREIGN KEY ( MECZ_ID_MECZU ) 
REFERENCES MECZ ( ID_MECZU ) ;

ALTER TABLE ZDARZENIE 
ADD CONSTRAINT ZDARZENIE_OSOBA_FK 
FOREIGN KEY ( ZAWODNIK_1_ID_OSOBY ) 
REFERENCES OSOBA ( ID_OSOBY ) ;

ALTER TABLE ZDARZENIE 
ADD CONSTRAINT ZDARZENIE_OSOBA_FKv1 
FOREIGN KEY ( ZAWODNIK_2_ID_OSOBY ) 
REFERENCES OSOBA ( ID_OSOBY ) ;

ALTER TABLE ZDARZENIE 
ADD CONSTRAINT ZDARZENIE_SEDZIA_MECZ_FK 
FOREIGN KEY ( SEDZIA_MECZ_ID_SEDZIEGO ) 
REFERENCES SEDZIA_MECZ ( ID_SEDZIEGO ) ;

ALTER TABLE ZDARZENIE 
ADD CONSTRAINT ZDARZENIE_TYP_ZDARZENIA_FK 
FOREIGN KEY ( TYP_ZDARZENIA_ID_TYPU ) 
REFERENCES TYP_ZDARZENIA ( ID_TYPU ) ;


--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


--Wstawianie Pozycji Zawodnikow
INSERT INTO POZYCJA VALUES(POZYCJA_SEQ.NEXTVAL, 'Bramkarz');
INSERT INTO POZYCJA VALUES(POZYCJA_SEQ.NEXTVAL, 'Obroñca');
INSERT INTO POZYCJA VALUES(POZYCJA_SEQ.NEXTVAL, 'Pomocnik');
INSERT INTO POZYCJA VALUES(POZYCJA_SEQ.NEXTVAL, 'Napastnik');
INSERT INTO POZYCJA VALUES(POZYCJA_SEQ.NEXTVAL, 'Rezerwowy');

--Wstawianie Klas Sedziow
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'Zawodowy');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'TopAmator');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'III Liga');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'IV Liga');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'Okrêgowy');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'A');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'B');
INSERT INTO KLASA_SEDZIEGO VALUES(KLASA_SEDZIEGO_SEQ.NEXTVAL, 'C');

--Wstawienie Typów Zdarzeñ
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Gol');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Out');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Faul');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Rzut Ro¿ny');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Rzut Karny');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Zó³ta Kartka');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Czerwona Kartka');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Zmiana Zawodników');
INSERT INTO TYP_ZDARZENIA VALUES(TYP_SEQ.NEXTVAL, 'Rzut Wolny');

--Wstawianie Osob - Sedziowie
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'John', 'Hover', '1989-4-7','Nowy Jork','USA');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Marian', 'Grzyb', '1985-9-11','Kraków','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Martin', 'Older', '1988-1-22','Warszawa','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Tomas', 'Woch', '1984-4-23','Gdynia','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Maciej', 'Koch', '1982-2-16','Kraków','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jerzy', 'Szklanka', '1992-6-11','Kielce','Polska');

--Wstawianie Osob - Szefowie
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Victor', 'Shazam', '1979-4-7','Witebsk','Bia³oruœ');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Olgierd', 'Leszcz', '1975-9-11','£ódŸ','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jerzy', 'Sola', '1976-1-22','Rzeszów','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Daniel', 'Frank', '1964-4-23','Drezno','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Michael', 'Mobo', '1972-2-16','Lyon','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Adam', 'Koch', '1982-6-21','Wroc³aw','Polska');

--Wstawianie Osob - Trenerzy
--Francja
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Didier', 'Deschamps', '1968-10-15','Bayonne','Francja');
--Polska
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Adam', 'Nawa³ka', '1957-10-23','Kraków','Polska');
--Niemcy
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Joachim', 'Löw', '1960-2-3','Schönau','Niemcy');
--Portugalia
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Fernando', 'Santos', '1954-10-10','Lizbona','Portugalia');

--Wstawianie Osob - Zawodnicy - Francja
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Hugo', 'Lloris', '1986-12-26','Nicea','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Christophe', 'Jallet', '1983-10-31','Cognac','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Patrice', 'Evra', '1981-5-15','Dakar','Senegal');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Adil', 'Rami', '1985-12-27','Bastia','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'N’Golo', 'Kanté', '1991-3-29','Pary¿','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Yohan', 'Cabaye', '1986-1-14','Tourcoing','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Antoine', 'Griezmann', '1991-3-21','Mâcon','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Dimitri', 'Payet', '1987-3-29','Saint-Pierre','Reunion');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Olivier', 'Giroud', '1986-9-30','Chambéry','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'André-Pierre', 'Gignac', '1985-12-5','Martigues','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Anthony', 'Martial', '1995-12-5','Massy','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Morgan', 'Schneiderlin', '1989-11-8','Zellwiller','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Eliaquim', 'Mangala', '1991-2-13','Pary¿','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Blaise', 'Matuidi', '1987-4-9','Tuluza','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Paul', 'Pogba', '1993-3-15','Lagny-sur-Marne','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Steve', 'Mandanda', '1985-3-28','Kinszasa','Demokratyczna Republika Konga');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Lucas', 'Digne', '1993-7-20','Meaux','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Moussa', 'Sissoko', '1989-8-16','Blanc-Mesnil','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Bacary', 'Sagna', '1983-2-14','Sens','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Kingsley', 'Coman', '1996-6-13','Pary¿','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Laurent', 'Koscielny', '1985-9-10','Tulle','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Samuel', 'Umtiti', '1993-11-14','Jaunde','Kamerun');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Benoît', 'Costil', '1987-7-3','Caen','Francja');
--.......

--Wstawianie Osob - Zawodnicy - Polska
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, '£ukasz', 'Piszczek', '1985-6-3','Czechowice-Dziedzice','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jakub', 'B³aszczykowski', '1985-12-14','Truskolasy','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Robert', 'Lewandowski', '1988-6-21','Warszawa','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Kamil', 'Grosicki', '1988-6-8','Szczecin','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Micha³', 'Pazdan', '1987-9-21','Kraków','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Kamil', 'Glik', '1988-2-3','Jastrzêbie-Zdrój','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Artur', 'Jêdrzejczyk', '1987-11-4','Dêbica','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Grzegorz', 'Krychowiak', '1990-1-29','Gryfice','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Tomasz', 'Jod³owiec', '1985-9-8','¯ywiec','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Arkadiusz', 'Milik', '1994-2-28','Tychy','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, '£ukasz', 'Fabiañski', '1985-4-18','Kostrzyn nad Odr¹','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Bartosz', 'Kapustka', '1996-12-23','Tarnów','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Krzysztof', 'M¹czyñski', '1987-5-23','Kraków','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Artur', 'Boruc', '1980-2-20','Siedlce','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'S³awomir', 'Peszko', '1985-2-19','Jas³o','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Wojciech', 'Szczêsny', '1990-4-18','Warszawa','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jakub', 'Wawrzyniak', '1983-7-7','Kutno','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Thiago', 'Cionel', '1986-4-21','Kurytyba','Brazylia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Piotr', 'Zieliñski ', '1994-5-20','Z¹bkowice Œl¹skie','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Filip', 'Starzyñski ', '1991-5-27','Szczecin','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Karol', 'Linetty', '1995-2-2','¯nin','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Mariusz', 'Stêpiñski', '1995-5-12','Sieradz','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Bartosz', 'Salamon', '1991-5-1','Poznañ','Polska');
--.......

--Wstawianie Osob - Zawodnicy - Niemcy
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Manuel', 'Neuer', '1986-3-27','Gelsenkirchen','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Shkodran', 'Mustafi', '1992-4-17','Bad Hersfeld','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jonas', 'Hector', '1990-5-27','Saarbrücken','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Benedikt', 'Höwedes', '1988-2-29','Haltern am See','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Mats', 'Hummels', '1988-12-16','Bensberg','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Sami', 'Khedira', '1987-4-4','Stuttgart','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Bastian', 'Schweinsteiger', '1984-6-1','Kolbermoor','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Mesut', 'Özil', '1986-10-15','Gelsenkirchen','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'André', 'Schürrle', '1990-11-6','Ludwigshafen am Rhein','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Lukas', 'Podolski', '1985-6-4','Gliwice','Polska');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Julian', 'Draxler', '1993-9-20','Gladbeck','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Bernd', 'Leno', '1992-3-4','Bietigheim-Bissingen','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Thomas', 'Müller', '1989-9-13','Weilheim in Oberbayern','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Emre', 'Can ', '1994-1-12','Frankfurt nad Menem','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Julian', 'Weigl', '1995-9-8','Bad Aibling','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jonathan', 'Tah', '1996-2-11','Hamburg','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Jérôme', 'Boateng', '1988-9-3','Berlin','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Toni', 'Kroos', '1990-1-4','Greifswald','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Mario', 'Götze', '1992-8-3','Memmingen','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Leroy', 'Sané', '1996-1-11','Essen','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Joshua', 'Kimmich', '1995-2-8','Rottweil','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Marc-André', 'ter Stegen', '1992-4-30','Mönchengladbach ','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Mario', 'Gómez', '1985-7-10','Riedlingen ','Niemcy');
--.......

--Wstawianie Osob - Zawodnicy - Portugalia
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Rui', 'Patrício', '1988-2-15','Leiria','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Képler "Pepe"', 'Ferreira', '1983-2-26','Maceió','Brazylia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Anthony', 'Lopes', '1990-10-1','Gibors','Franca');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Eduardo', 'dos Reis Carvalho', '1982-9-19','Mirandela','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Bruno', 'Alves', '1981-11-27','Póvoa de Varzim','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'José', 'Fonte', '1983-12-22','Penafie','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Raphaël', 'Guerreiro', '1993-12-22','Blanc-Mesnil','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Ricardo', 'Carvalho', '1978-5-18','Amarante','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Eliseu', 'Pereira dos Santos', '1983-8-1','Angra do Heroísmo','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Cédric', 'Soares', '1991-8-31','Singen','Niemcy');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Joao', 'Moutinh', '1986-9-8','Portimao','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Joao Mário', 'Eduardo', '1993-1-19','Porto','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Adelino André Vieira "Vieirinha"', 'de Freitas', '1986-1-24','Guimaraes','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Danilo', 'Pereira', '1991-9-9','Bissau','Gwinea Bissau');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'William', 'Carvalho', '1992-4-7','Luanda','Angola');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'André', 'Gomes', '1993-7-30','Grijó','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Renato', 'Sanches', '1997-8-18','Lizbona','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Adrien', 'Silva', '1989-3-15','Angouleme','Francja');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Cristiano', 'Ronaldo', '1985-2-5','Funchal','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Éderzito "Éder"', 'Lopes', '1987-12-22','Bissau','Gwinea Bissau');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Luís Carlos Almeida "Nani"', 'da Cunha', '1986-11-17','Praia','Republiki Zielonego Przyl¹dka');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Rafael Ferreira', 'Silva', '1993-5-17','Forte da Casa','Portugalia');
INSERT INTO OSOBA VALUES(OSOBA_SEQ.NEXTVAL, 'Ricardo', 'Quaresma', '1983-9-26','Vila Nova de Famalicao','Portugalia');
--.......

--Wstawianie Klubów
--Francuski
INSERT INTO KLUB VALUES(KLUB_SEQ.NEXTVAL,'Olympique Marsylia', '1899-08-31', 2010, 2012);
--Polska
INSERT INTO KLUB VALUES(KLUB_SEQ.NEXTVAL,'Lech Poznañ', '1922-03-19', 2008, 2013);
--Niemcy
INSERT INTO KLUB VALUES(KLUB_SEQ.NEXTVAL,'Borussia Dortmund', '1909-12-19', 2009, 2014);
--Portugalia
INSERT INTO KLUB VALUES(KLUB_SEQ.NEXTVAL,'Sporting Lizbona', '1906-04-14', 2006, 2015);

--Wstawianie Dru¿yn
INSERT INTO DRUZYNA VALUES(DRUZYNA_SEQ.NEXTVAL, 'OM Team Front', 3000);
INSERT INTO DRUZYNA VALUES(DRUZYNA_SEQ.NEXTVAL, 'LP Zieloni', 3001);
INSERT INTO DRUZYNA VALUES(DRUZYNA_SEQ.NEXTVAL, 'BD Berlin', 3002);
INSERT INTO DRUZYNA VALUES(DRUZYNA_SEQ.NEXTVAL, 'SP Ronald', 3003);

--Wstawianie Stadionów
INSERT INTO STADION VALUES(STADION_SEQ.NEXTVAL, 'Stade Vélodrome', 'Marsylia', 3000);
INSERT INTO STADION VALUES(STADION_SEQ.NEXTVAL, 'Stadion Narodowy', 'Warszawa', 3001);
INSERT INTO STADION VALUES(STADION_SEQ.NEXTVAL, 'Signal Iduna Park', 'Dortmund', 3002);
INSERT INTO STADION VALUES(STADION_SEQ.NEXTVAL, 'Estádio José Alvalade', 'Lizbona', 3003);

--Wstawianie Sêdziów i nadanie im klas
INSERT INTO SEDZIA_MECZ VALUES(SEDZIA_SEQ.NEXTVAL, 2000, 100);
INSERT INTO SEDZIA_MECZ VALUES(SEDZIA_SEQ.NEXTVAL, 2001, 100);
INSERT INTO SEDZIA_MECZ VALUES(SEDZIA_SEQ.NEXTVAL, 2002, 101);
INSERT INTO SEDZIA_MECZ VALUES(SEDZIA_SEQ.NEXTVAL, 2003, 101);
INSERT INTO SEDZIA_MECZ VALUES(SEDZIA_SEQ.NEXTVAL, 2004, 100);
INSERT INTO SEDZIA_MECZ VALUES(SEDZIA_SEQ.NEXTVAL, 2005, 100);


--Wstawienie Meczy
INSERT INTO MECZ VALUES (MECZ_SEQ.NEXTVAL, '2015-03-10', '92:10', 6000, 6001, 5001, 1000, 1001, 1002);
INSERT INTO MECZ VALUES (MECZ_SEQ.NEXTVAL, '2014-05-14', '90:55', 6002, 6003, 5002, 1003, 1004, 1005);
INSERT INTO MECZ VALUES (MECZ_SEQ.NEXTVAL, '2016-07-18', '95:05', 6003, 6000, 5003, 1001, 1003, 1002);
INSERT INTO MECZ VALUES (MECZ_SEQ.NEXTVAL, '2013-07-15', '91:45', 6002, 6001, 5002, 1005, 1000, 1003);

--Przypisywanie zawodnikow do druzyn i meczy w których brali udzial

-----------------------------------------------------------------------
-- Mecz ID 7000
-----------------------------------------------------------------------
-- Francja ----------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 200, 2016, 6000); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2017, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2018, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2017, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2018, 6000);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2019, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2020, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2021, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2022, 6000);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 203, 2023, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 203, 2024, 6000);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2025, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2026, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2027, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2028, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2029, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2030, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2031, 6000);

-- Polska ---------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 200, 2039, 6001); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2040, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2041, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2042, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 201, 2043, 6001);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2044, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2045, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2046, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 202, 2047, 6001);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 203, 2048, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 203, 2049, 6001);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2050, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2051, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2052, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2053, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2054, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2055, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7000, 204, 2056, 6001);


-----------------------------------------------------------------------
-- Mecz ID 7001
-----------------------------------------------------------------------
-- Niemcy ------------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 200, 2062, 6002); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2063, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2064, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2065, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2066, 6002);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2067, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2068, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2069, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2070, 6002);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 203, 2071, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 203, 2072, 6002);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2073, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2074, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2075, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2076, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2077, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2078, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2079, 6002);

-- Portugalia -------------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 200, 2085, 6003); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2086, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2087, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2088, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 201, 2089, 6003);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2090, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2091, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2092, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 202, 2093, 6003);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 203, 2094, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 203, 2095, 6003);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2096, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2097, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2098, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2099, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2100, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2101, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7001, 204, 2102, 6003);


-----------------------------------------------------------------------
-- Mecz ID 7002
-----------------------------------------------------------------------
-- Francja ----------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 200, 2016, 6000); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2017, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2018, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2017, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2018, 6000);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2019, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2020, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2021, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2022, 6000);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 203, 2023, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 203, 2024, 6000);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2025, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2026, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2027, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2028, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2029, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2030, 6000);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2031, 6000);


-- Portugalia -------------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 200, 2085, 6003); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2086, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2087, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2088, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 201, 2089, 6003);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2090, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2091, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2092, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 202, 2093, 6003);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 203, 2094, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 203, 2095, 6003);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2096, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2097, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2098, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2099, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2100, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2101, 6003);
INSERT INTO ZAWODNIK_MECZ VALUES(7002, 204, 2102, 6003);


-----------------------------------------------------------------------
-- Mecz ID 7003
-----------------------------------------------------------------------
-- Niemcy ------------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 200, 2062, 6002); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2063, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2064, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2065, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2066, 6002);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2067, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2068, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2069, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2070, 6002);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 203, 2071, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 203, 2072, 6002);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2073, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2074, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2075, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2076, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2077, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2078, 6002);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2079, 6002);

-- Polska ---------------------
--Bramkarz
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 200, 2039, 6001); 
--Obroncy
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2040, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2041, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2042, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 201, 2043, 6001);
--Pomocnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2044, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2045, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2046, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 202, 2047, 6001);
--Napastnicy
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 203, 2048, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 203, 2049, 6001);
--Rezerwowi
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2050, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2051, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2052, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2053, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2054, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2055, 6001);
INSERT INTO ZAWODNIK_MECZ VALUES(7003, 204, 2056, 6001);
-----------------------------------------------------------------------

--Wstawienie zdarzen do meczy

--Zdarzenia w meczu id 7003
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '54:32', 2048, NULL, 7003, 1005);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '84:32', 2049, NULL, 7003, 1005);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '34:32', 2071, NULL, 7003, 1005);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '44:32', 2072, NULL, 7003, 1005);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4002, '77:32', 2067, 2047, 7003, 1005);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4002, '79:32', 2062, 2047, 7003, 1005);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4001, '22:32', 2062, 2045, 7003, 1005);

--Zdarzenia w meczu id 7002
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '64:32', 2095, NULL, 7002, 1001);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '24:32', 2094, NULL, 7002, 1001);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4005, '44:32', 2023, NULL, 7002, 1001);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4005, '54:32', 2024, NULL, 7002, 1001);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '34:32', 2024, NULL, 7002, 1001);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4007, '74:22', 2020, 2027, 7002, 1001);

--Zdarzenia w meczu id 7001
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '55:32', 2070, NULL, 7001, 1003);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '22:32', 2072, NULL, 7001, 1003);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4002, '48:32', 2091, 2067, 7001, 1003);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '11:32', 2094, NULL, 7001, 1003);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4003, '13:22', 2072, NULL, 7001, 1003);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4001, '23:22', 2086, 2070, 7000, 1000);

--Zdarzenia w meczu id 7000
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4005, '34:32', 2023, NULL, 7000, 1000);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4008, '84:22', 2024, NULL, 7000, 1000);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4001, '14:22', 2045, 2020, 7000, 1000);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4000, '65:32', 2023, NULL, 7000, 1000);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4001, '23:22', 2041, 2022, 7000, 1000);
INSERT INTO ZDARZENIE VALUES (ZDARZENIE_SEQ.NEXTVAL, 4007, '23:22', 2044, 2053, 7000, 1000);


--------------------------------------------------------------------------------
------------------ 1 - WIDOK OGOLNEJ ILOSCI GOLI ZAWODNIKOW --------------------
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW ZAWODNIK_GOLE AS 
SELECT 
  ZAWODNIK_ID_OSOBY,
  IMIE,
  NAZWISKO,
  COUNT (*) ILOSC_GOLI 
FROM ZAWODNIK_MECZ
  JOIN ZDARZENIE
    ON ZDARZENIE.ZAWODNIK_1_ID_OSOBY = ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY
  JOIN OSOBA
    ON OSOBA.ID_OSOBY = ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY
WHERE ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4000
GROUP BY
    ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY,
    IMIE,
    NAZWISKO
ORDER BY ILOSC_GOLI DESC;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
----- 2 - WIDOK WYSWIETLA INFORMACJE O STADIONACH I ILOSC ROZEGRANYCH MECZY ----
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW STADION_INFO AS 
SELECT
  STADION.ID_STADIONU,
  STADION.NAZWA AS NAZWA,
  STADION.LOKALIZACJA,
  KLUB.NAZWA AS NALEZY_DO,
  COUNT (*) AS ILOSC_MECZY,
  NAZWISKO AS NAZWISKO_SZEFA_KLUBU,
  IMIE AS IMIE_SZEFA_KLUBU  
FROM STADION  
  JOIN KLUB
    ON KLUB.ID_KLUBU = STADION.KLUB_ID_KLUBU
  JOIN MECZ
    ON MECZ.STADION_ID_STADIONU = STADION.ID_STADIONU
  JOIN OSOBA
    ON OSOBA.ID_OSOBY = KLUB.SZEF_ID_OSOBY    
GROUP BY 
  STADION.ID_STADIONU,
  STADION.NAZWA,
  STADION.LOKALIZACJA,
  KLUB.NAZWA,
  OSOBA.IMIE,
  OSOBA.NAZWISKO 
ORDER BY ILOSC_MECZY DESC;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
----------------- 3 - WIDOK INFORMACJI O WSZYSTKICH SEDZIACH -------------------
--------------------------------------------------------------------------------

CREATE OR REPLACE VIEW SEDZIA_INFO AS
SELECT
  SEDZIA_MECZ.ID_SEDZIEGO,
  OSOBA.NAZWISKO,
  OSOBA.IMIE,
  OSOBA.NARODOWOSC,
  KLASA_SEDZIEGO.NAZWA_KLASY AS KLASA_SEDZIEGO,
  TRUNC(MONTHS_BETWEEN(sysdate, OSOBA.DATA_URODZENIA)/12) AS WIEK,
  COUNT (*) AS ILOSC_MECZY  
FROM OSOBA
  JOIN SEDZIA_MECZ
    ON SEDZIA_MECZ.OSOBA_ID_OSOBY = OSOBA.ID_OSOBY
  JOIN KLASA_SEDZIEGO
    ON KLASA_SEDZIEGO.ID_KLASY = SEDZIA_MECZ.KLASA_SEDZIEGO_ID_KLASY
  JOIN MECZ
    ON MECZ.SEDZIA_MECZ_ID_OSOBY_SEDZIA_1 = SEDZIA_MECZ.ID_SEDZIEGO
      OR MECZ.SEDZIA_MECZ_ID_OSOBY_SEDZIA_2 = SEDZIA_MECZ.ID_SEDZIEGO
      OR MECZ.SEDZIA_MECZ_ID_OSOBY_SEDZIA_3 = SEDZIA_MECZ.ID_SEDZIEGO
GROUP BY  
  SEDZIA_MECZ.ID_SEDZIEGO,
  OSOBA.NAZWISKO,
  OSOBA.IMIE,
  OSOBA.NARODOWOSC,
  TRUNC(MONTHS_BETWEEN(sysdate, OSOBA.DATA_URODZENIA)/12),
  KLASA_SEDZIEGO.NAZWA_KLASY
ORDER BY OSOBA.NAZWISKO;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
----------------- 4 - WIDOK INFORMACJI O WSZYSTKICH KLUBACH --------------------
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW KLUBY_INFO AS
SELECT NAZWA AS Nazwa,
DATA_ZALOZENIA AS Data_zalozenia,
(SELECT IMIE FROM OSOBA WHERE OSOBA.ID_OSOBY = KLUB.SZEF_ID_OSOBY) AS Imie_szefa,
(SELECT NAZWISKO FROM OSOBA WHERE OSOBA.ID_OSOBY = KLUB.SZEF_ID_OSOBY) AS Nazwisko_szefa,
(SELECT IMIE FROM OSOBA WHERE OSOBA.ID_OSOBY = KLUB.TRENER_ID_OSOBY) AS Imie_trenera,
(SELECT NAZWISKO FROM OSOBA WHERE OSOBA.ID_OSOBY = KLUB.TRENER_ID_OSOBY) AS Nazwisko_trenera
FROM KLUB;
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--------- 1 - FUNKCJA ZWRACA ILOSC KARTEK W MECZU O ID Z ARGUMENTU -------------
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION FUN_MECZ_ILOSC_KARTEK(ID_M IN INTEGER) 
RETURN INTEGER IS

  I_ILOSC_KARTEK INTEGER := 0 ;

CURSOR CUR_MECZ_ILOSC_KARTEK IS
  
  SELECT DISTINCT
  
    COUNT (*) AS ILOSC_KARTEK INTO I_ILOSC_KARTEK
    
  FROM ZDARZENIE
  
    JOIN TYP_ZDARZENIA 
      ON ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = TYP_ZDARZENIA.ID_TYPU
  
  WHERE (ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4005 
      OR ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4006)
     AND ZDARZENIE.MECZ_ID_MECZU = ID_M
  
  ORDER BY ILOSC_KARTEK DESC;
    
BEGIN
  OPEN CUR_MECZ_ILOSC_KARTEK;
    FETCH CUR_MECZ_ILOSC_KARTEK INTO I_ILOSC_KARTEK;   
  CLOSE CUR_MECZ_ILOSC_KARTEK;
  RETURN (I_ILOSC_KARTEK);
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
------------ 2 - FUNKCJA ZWRACA SREDNI WIEK ZAWODNIKOW W KLUBIE ----------------
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION FUN_AVG_WIEKU_ZAW_KLUBU (ID_K IN INTEGER) 
RETURN INTEGER IS

  TMP_WIEK INTEGER := 0.0 ;
  TMP_SUMA INTEGER := 0;
  TMP_ID_ZAW INTEGER := 0;
  TMP_LICZNIK INTEGER := 0;

CURSOR CUR_WIEK_ZAW_KLUBU IS
  
  SELECT DISTINCT
    ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY,
    TRUNC(MONTHS_BETWEEN(sysdate, OSOBA.DATA_URODZENIA)/12) AS WIEK

  FROM OSOBA

    JOIN ZAWODNIK_MECZ
      ON ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY = OSOBA.ID_OSOBY
    JOIN DRUZYNA
      ON DRUZYNA.ID_DRUZYNY = ZAWODNIK_MECZ.DRUZYNA_ID_DRUZYNY

  WHERE DRUZYNA.KLUB_ID_KLUBU = ID_K

  ORDER BY WIEK DESC;

BEGIN
  OPEN CUR_WIEK_ZAW_KLUBU;
  LOOP
    FETCH CUR_WIEK_ZAW_KLUBU INTO TMP_ID_ZAW, TMP_WIEK;
    EXIT WHEN (CUR_WIEK_ZAW_KLUBU%NOTFOUND);
    TMP_SUMA := TMP_SUMA + TMP_WIEK;
    TMP_LICZNIK := TMP_LICZNIK + 1;
  END LOOP;
  CLOSE CUR_WIEK_ZAW_KLUBU;
  RETURN (TMP_SUMA/TMP_LICZNIK);
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-------------- 3 - FUNKCJA ZWRACA NAZWY KLUBOW I WYNIK W MECZU -----------------
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION FUN_WYNIK_MECZU (ID_M IN INTEGER) 
RETURN VARCHAR2 IS

  TMP_WYNIK_KLUB_1  INTEGER := 0;
  TMP_WYNIK_KLUB_2  INTEGER := 0;
  TMP_NAZWA_KLUB_1  VARCHAR(30) := '';
  TMP_NAZWA_KLUB_2  VARCHAR(30) := '';
  TMP_TMP           VARCHAR(30) := '';

--KURSOR Z NAZWAMI KLUBOW W MECZU
CURSOR CUR_KLUBY_MECZU IS SELECT DISTINCT

  KLUB.NAZWA AS NAZWA_KLUBU

FROM MECZ

  JOIN DRUZYNA 
    ON DRUZYNA.ID_DRUZYNY = MECZ.DRUZYNA_ID_DRUZYNY_1
    OR DRUZYNA.ID_DRUZYNY = MECZ.DRUZYNA_ID_DRUZYNY_2
  JOIN KLUB
    ON KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU

  WHERE MECZ.ID_MECZU = ID_M
     
ORDER BY KLUB.NAZWA DESC;
 
--KURSOR Z NAZWAMI KLUBOW I LICZBA GOLI    
CURSOR CUR_GOLE_KLUBY_MECZU IS SELECT DISTINCT
  
  KLUB.NAZWA,
  COUNT (*) AS ILOSC_GOLI

FROM ZDARZENIE

  JOIN ZAWODNIK_MECZ 
    ON ZDARZENIE.ZAWODNIK_1_ID_OSOBY = ZAWODNIK_MECZ.ZAWODNIK_ID_OSOBY
    AND ZDARZENIE.MECZ_ID_MECZU = ZAWODNIK_MECZ.MECZ_ID_MECZU
  JOIN DRUZYNA 
    ON DRUZYNA.ID_DRUZYNY = ZAWODNIK_MECZ.DRUZYNA_ID_DRUZYNY
  JOIN TYP_ZDARZENIA 
    ON ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = TYP_ZDARZENIA.ID_TYPU
  JOIN KLUB
    ON KLUB.ID_KLUBU = DRUZYNA.KLUB_ID_KLUBU

  WHERE ZDARZENIE.MECZ_ID_MECZU = ID_M
    AND ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4000
    
GROUP BY 
  KLUB.NAZWA,
  ZDARZENIE.TYP_ZDARZENIA_ID_TYPU

ORDER BY KLUB.NAZWA DESC;

BEGIN

  OPEN CUR_KLUBY_MECZU;
  FETCH CUR_KLUBY_MECZU INTO TMP_NAZWA_KLUB_1;
  FETCH CUR_KLUBY_MECZU INTO TMP_NAZWA_KLUB_2;
  CLOSE CUR_KLUBY_MECZU;

  OPEN CUR_GOLE_KLUBY_MECZU;
  
  --JESLI NIE BEDZIE GOLI TO ZOSTANIE ZERO
  FETCH CUR_GOLE_KLUBY_MECZU INTO TMP_TMP, TMP_WYNIK_KLUB_1;
  
  --JESLI NIE BEDZIE GOLI TO ZOSTANIE ZERO
  FETCH CUR_GOLE_KLUBY_MECZU INTO TMP_TMP, TMP_WYNIK_KLUB_2;
 
  CLOSE CUR_GOLE_KLUBY_MECZU;
  
  RETURN
  (
    TO_CHAR
    (
      TMP_NAZWA_KLUB_1 || ' ' || 
      TO_CHAR(TMP_WYNIK_KLUB_1) || ' : ' || 
      TO_CHAR(TMP_WYNIK_KLUB_2) || ' ' || 
      TMP_NAZWA_KLUB_2
    )
  );
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
--- 4 - FUNKCJA ZWRACA PROCENT ZDARZENIA WZGLEDEM WSZYSTKICH ZDARZEN W MECZU ---
--------------------------------------------------------------------------------
SET SERVEROUTPUT ON
CREATE OR REPLACE 
FUNCTION FUN_PROC_ZDARZENIE_MECZ (ID_M IN INTEGER, ID_Z IN INTEGER) 
RETURN INTEGER IS

  TMP_ILOSC_WSZYSTKICH_ZDARZEN INTEGER;
  TMP_ILOSC_WSKAZANYCH_ZDARZEN INTEGER;

BEGIN

  SELECT 
    COUNT(*) INTO TMP_ILOSC_WSZYSTKICH_ZDARZEN 
  FROM ZDARZENIE 
  WHERE MECZ_ID_MECZU = ID_M;
  
  SELECT 
    COUNT(*) INTO TMP_ILOSC_WSKAZANYCH_ZDARZEN 
  FROM ZDARZENIE 
  WHERE MECZ_ID_MECZU = ID_M
    AND TYP_ZDARZENIA_ID_TYPU = ID_Z;
  
  
  RETURN((TMP_ILOSC_WSKAZANYCH_ZDARZEN/TMP_ILOSC_WSZYSTKICH_ZDARZEN)*100);
END;
/
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
----- 1 - WYZWALACZ SPRAWDZA MOZLIWOSC DODANIA ZAWODNIKOWI KARTKI W MECZU ------
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TGR_KONTROLA_KARTEK
BEFORE INSERT OR UPDATE ON ZDARZENIE FOR EACH ROW

DECLARE

  TMP_ILOSC_KARTEK_Z_ZAW INTEGER := 0;
  TMP_ILOSC_KARTEK_C_ZAW INTEGER := 0;
  
BEGIN
  SELECT 
    COUNT(*) INTO TMP_ILOSC_KARTEK_Z_ZAW
    
  FROM ZDARZENIE
  WHERE ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4005
      AND ZAWODNIK_1_ID_OSOBY = :NEW.ZAWODNIK_1_ID_OSOBY
      AND ZDARZENIE.MECZ_ID_MECZU = :NEW.MECZ_ID_MECZU;
      
  SELECT 
    COUNT(*) INTO TMP_ILOSC_KARTEK_C_ZAW
    
  FROM ZDARZENIE
  WHERE ZDARZENIE.TYP_ZDARZENIA_ID_TYPU = 4006
      AND ZAWODNIK_1_ID_OSOBY = :NEW.ZAWODNIK_1_ID_OSOBY
      AND ZDARZENIE.MECZ_ID_MECZU = :NEW.MECZ_ID_MECZU;
  
  IF (TMP_ILOSC_KARTEK_Z_ZAW > 0 AND :NEW.TYP_ZDARZENIA_ID_TYPU = 4005) THEN
  RAISE_APPLICATION_ERROR
  (-20000, 'Temu Zawodnikowi Nie Mozna Juz Dac Zoltej Kartki W Tym Meczu'); 
  END IF;
  
  IF (TMP_ILOSC_KARTEK_C_ZAW > 0 AND :NEW.TYP_ZDARZENIA_ID_TYPU = 4006) THEN
  RAISE_APPLICATION_ERROR
  (-20000, 'Temu Zawodnikowi Nie Mozna Juz Dac Czerwonej Kartki W Tym Meczu'); 
  END IF;

END;
/

--------------------------------------------------------------------------------
----------------- 2 - WYZWALACZ WSTAWIA LOGI ZMIAN DANYCH OSOB  -----------------
--------------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TGR_LOG_OSOBA 
AFTER UPDATE ON OSOBA FOR EACH ROW

BEGIN 
  CASE WHEN UPDATING THEN
  INSERT INTO OSOBA_LOG VALUES
  (
    LOG_SEQ.NEXTVAL,
    SYSDATE,
    :OLD.ID_OSOBY,
    :OLD.IMIE,
    :OLD.NAZWISKO,
    :OLD.DATA_URODZENIA,
    :OLD.MIEJSCE_URODZENIA,
    :OLD.NARODOWOSC
  );
  END CASE;
END;
/

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


