--Tworzenie Sekwencji
CREATE SEQUENCE KLASA_SEDZIEGO_SEQ START WITH 100 INCREMENT BY 1;
CREATE SEQUENCE POZYCJA_SEQ START WITH 200 INCREMENT BY 1;
CREATE SEQUENCE SEDZIA_SEQ START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE OSOBA_SEQ START WITH 2000 INCREMENT BY 1;
CREATE SEQUENCE KLUB_SEQ START WITH 3000 INCREMENT BY 1;
CREATE SEQUENCE TYP_SEQ START WITH 4000 INCREMENT BY 1;
CREATE SEQUENCE STADION_SEQ START WITH 5000 INCREMENT BY 1;
CREATE SEQUENCE DRUZYNA_SEQ START WITH 6000 INCREMENT BY 1;
CREATE SEQUENCE MECZ_SEQ START WITH 7000 INCREMENT BY 1;
CREATE SEQUENCE ZDARZENIE_SEQ START WITH 8000 INCREMENT BY 1;
CREATE SEQUENCE LOG_SEQ START WITH 9000 INCREMENT BY 1;